import os
import pandas as pd


bold = "\033[1m"
green = "\033[92m"
cyan = "\033[36m"
end = "\033[0m"


msg = f"""{cyan}Bacterial-rnaseq-deseq: A Snakemake workflow
for differential expression analysis of RNAseq data.{end}"""


# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/deseq2.smk"


module rnaseq_processing:
    snakefile:
        github(
            "MPUSP/snakemake-bacterial-rnaseq-processing",
            path="workflow/Snakefile",
            branch="main",
        )
    config:
        config


use rule * from rnaseq_processing as process_*


onstart:
    print("\n--- Analysis started...\n")
    print()
    print("--- Analysis parameters --------------------------------------------\n")
    print(f"Current working directory: {os.getcwd()}")
    print(f"Output directory: {os.path.join(os.getcwd(), 'results')}")
    print()
    print(f"RNAseq samples: {list(samples.index)}")
    print()


onsuccess:
    print()
    print(msg)
    print("--- Workflow finished, no error! -----------------------------------")
    print()
    debug = os.path.join(os.getcwd(), "results/workflow.log")
    shell(
        "cat {log} > {debug} && echo -e '\nWorkflow finished, no error!\n' >> {debug}"
    )


onerror:
    print()
    print(msg)
    print("--- An error occurred! ---------------------------------------------")
    print()
    error = os.path.join(os.getcwd(), "results/error.log")
    shell("cat {log} > {error} && echo -e '\nAn error occurred!' >> {error}")


# target rules
# # -----------------------------------------------------
rule all:
    input:
        "results/report/multiqc_report.html",
        "results/deseq2/deseq2_results.csv",
    default_target: True
