import os
import pandas as pd


# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/deseq2.smk"


module rnaseq_processing:
    snakefile:
        github(
            "MPUSP/snakemake-bacterial-rnaseq-processing",
            path="workflow/Snakefile",
            branch="main",
        )
    config:
        config


use rule * from rnaseq_processing as process_*


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    input:
        "results/report/multiqc_report.html",
        "results/deseq2/deseq2_results.csv",
    default_target: True
